name: droidcon_ke_flutter
description: DroidconKE Conference app built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0+1
  firebase_auth: ^0.11.1+11
  google_sign_in: ^4.0.4
  flutter_statusbarcolor: any
  cloud_firestore: any
  built_value: ^6.3.2
  built_collection: ^4.1.0
  shared_preferences: ^0.5.3+4
  google_maps_flutter: ^0.5.19+2
  permission_handler: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  built_value_generator: ^6.1.6
  build_test: any
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo-name.png
    - assets/images/google-signin.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
